name: Setup Labels

on:
  workflow_dispatch:

jobs:
  create-labels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Create labels
      uses: actions/github-script@v7
      with:
        script: |
          const labels = [
            {
              name: 'version:patch',
              description: 'Incrementa versão patch (1.0.0 → 1.0.1)',
              color: '28a745'
            },
            {
              name: 'version:minor', 
              description: 'Incrementa versão minor (1.0.0 → 1.1.0)',
              color: '007bff'
            },
            {
              name: 'version:major',
              description: 'Incrementa versão major (1.0.0 → 2.0.0)', 
              color: 'dc3545'
            }
          ];

          for (const label of labels) {
            try {
              await github.rest.issues.createLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label.name,
                description: label.description,
                color: label.color
              });
              console.log(`✅ Label '${label.name}' criada com sucesso!`);
            } catch (error) {
              if (error.status === 422) {
                console.log(`⚠️  Label '${label.name}' já existe`);
              } else {
                console.error(`❌ Erro ao criar label '${label.name}':`, error.message);
              }
            }
          }
